# Should the plugin check for updates on the Spigot page?
UpdateChecker: true
# LoggingLevel: Console logging level
# 0 means no logging at all
# 1 means basic logging
# 2 means extensive logging
LoggingLevel: 2
# Message to be displayed when a player doesn't have permission to execute a command
NoPermissionMessage: '&4You don''t have permission to do this!'
DoNotChange: 1.1.0