# Should the plugin check for updates on the Spigot page?
UpdateChecker: true
# The logging level, can be ALL, EXTENDED, NORMAL, MINIMAL, NOTHING
LogLevel: EXTENDED
# Message to be displayed when a player doesn't have permission to execute a command
NoPermissionMessage: '&4You don''t have permission to do this!'
DoNotChange: 1.3.1